# Generated by Django 6.0.3 on 2026-03-20 23:04

import django.core.validators
import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=270, unique=True)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=270)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('prompt', models.TextField(validators=[django.core.validators.MaxLengthValidator(10000)])),
                ('content', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('canon', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('generating', 'Generating'), ('done', 'Done'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('embedding', pgvector.django.vector.VectorField(dimensions=1536, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='series.chapter')),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=270)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('synopsis', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=7)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('like_count', models.PositiveIntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series', to=settings.AUTH_USER_MODEL)),
                ('genres', models.ManyToManyField(related_name='series', to='series.genre')),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_series', to=settings.AUTH_USER_MODEL)),
                ('spin_off', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spin_offs', to='series.series')),
                ('spin_off_chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spin_offs_started', to='series.chapter')),
            ],
        ),
        migrations.AddField(
            model_name='chapter',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='series.series'),
        ),
        migrations.CreateModel(
            name='World',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(validators=[django.core.validators.MaxLengthValidator(5000)])),
                ('embedding', pgvector.django.vector.VectorField(dimensions=1536, null=True)),
            ],
            options={
                'indexes': [pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='world_embedding_hnsw_idx', opclasses=['vector_cosine_ops'])],
            },
        ),
        migrations.AddField(
            model_name='series',
            name='world',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='series', to='series.world'),
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(validators=[django.core.validators.MaxLengthValidator(2000)])),
                ('embedding', pgvector.django.vector.VectorField(dimensions=1536, null=True)),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='series.series')),
            ],
            options={
                'indexes': [pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='character_embedding_hnsw_idx', opclasses=['vector_cosine_ops'])],
                'constraints': [models.UniqueConstraint(fields=('name', 'series'), name='unique_character_name_per_series')],
            },
        ),
        migrations.AddIndex(
            model_name='chapter',
            index=models.Index(fields=['series', 'canon'], name='chapter_series_canon_idx'),
        ),
        migrations.AddIndex(
            model_name='chapter',
            index=models.Index(fields=['series', '-created_at'], name='chapter_series_created_idx'),
        ),
        migrations.AddIndex(
            model_name='chapter',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='chapter_embedding_hnsw_idx', opclasses=['vector_cosine_ops']),
        ),
        migrations.AddConstraint(
            model_name='chapter',
            constraint=models.UniqueConstraint(fields=('slug', 'series'), name='unique_chapter_slug_per_series'),
        ),
        migrations.AddConstraint(
            model_name='chapter',
            constraint=models.UniqueConstraint(condition=models.Q(('canon', True)), fields=('parent', 'series'), name='unique_canon_child_per_parent'),
        ),
        migrations.AddConstraint(
            model_name='chapter',
            constraint=models.UniqueConstraint(condition=models.Q(('canon', True), ('parent__isnull', True)), fields=('series',), name='unique_canon_root_per_series'),
        ),
        migrations.AddConstraint(
            model_name='chapter',
            constraint=models.CheckConstraint(condition=models.Q(('canon', False), models.Q(('canon', True), ('status', 'done')), _connector='OR'), name='canon_chapter_must_be_done'),
        ),
        migrations.AddIndex(
            model_name='series',
            index=models.Index(fields=['visibility', '-created_at'], name='series_visibility_created_idx'),
        ),
        migrations.AddIndex(
            model_name='series',
            index=models.Index(fields=['author', '-created_at'], name='series_author_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='series',
            constraint=models.UniqueConstraint(fields=('slug', 'author'), name='unique_series_slug_per_author'),
        ),
        migrations.AddConstraint(
            model_name='series',
            constraint=models.CheckConstraint(condition=models.Q(('like_count__gte', 0)), name='like_count_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='series',
            constraint=models.CheckConstraint(condition=models.Q(('view_count__gte', 0)), name='view_count_non_negative'),
        ),
    ]
